# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'Jonathan Giuffrida'
tagline:          'Adventures in Data Analysis and Bunnies'
description:      'I live at the intersection of quantitative analysis, health policy, and the humanities.'
url:              https://jcgiuffrida.com
enforce_ssl:      jcgiuffrida.com
baseurl:          ''
author:
  name:           'Jonathan Giuffrida'
  url:            https://jcgiuffrida.com

timezone: America/New_York

plugins: [jekyll-paginate]

paginate:         5  # 5 posts per page
paginate_path:    '/projects/page:num/'

# Custom vars
version:          0.1

github:
  repo:           https://github.com/lucaluca/lucaluca.github.io
